tv2/tv-automation-server-core

meteor/lib/api/peripheralDevice.ts
meteor/server/api/ingest/api.ts
meteor/server/api/ingest/rundownInput.ts

`peripheralDevice.rundown.rundownList` will return an array of the rundown externalIds.
`peripheralDevice.rundown.rundownGet` will get the fill IngestRundown of the rundown/

feat: add peripheralDevice methods to list and get known rundowns

---

meteor/lib/collections/Pieces.ts
meteor/server/api/playout/infinites.ts
meteor/server/api/playout/timeline.ts

...to be used to easilly filter out old and cropped pieces.
This is intended to reduce the number of timeline-objects that are generated when adlibbing a lot.
_Note: I do not have the full overview of the implications of this hack. I've tested it locally and it seems to work, but I need some more sets of eyes on this before we dare deploy it to prod._
Basically, how it works:
* When we crop an infinite-piece, due to an exclusivity-group, I set the new `definitelyEnded`-propery to a time 10s into the future.
* When that time has passed, we'll filter out the content of the piece right away, so it won't render any timeline-objects
* The 10s allows for any transition to finish

fix/hack: Add property Piece.definitelyEnded

---

meteor/client/ui/Settings/components/PlayoutDeviceSettingsComponent.tsx

This PR adds the relevant config field for https://github.com/olzzon/tv-automation-state-timeline-resolver/pull/13
Set the value to 'disable' to disable retries, 0 for default or any other value in ms

feat: media retry config field

---

meteor/client/styles/settings.scss
meteor/client/ui/Settings/ConfigManifestSettings.tsx

* **What kind of change does this PR introduce?** 
- Makes the headers in big tables (e.g. GFX Templates) sticky.
- Makes those tables fit screen height and have their scrollbars and buttons visible for easier usage.
- Shortens numeric inputs to make the tables more compact.
- Adds optional sorting to tables by string and numeric columns.

Feat/settings improvements (tables)

---

meteor/client/styles/editAttribute.scss
meteor/client/ui/Settings/components/PlayoutDeviceSettingsComponent.tsx

This PR adds a _Clear-All Commands_ setting for the VizMSE device. 
In a textarea, multiple commands can be entered in separate lines. 
These commands are sent to Viz Engines in order to fully clear their outputs, which is triggered by a `TimelineObjVIZMSEClearAllElements` and on `makeReady`.
It depends on https://github.com/olzzon/tv-automation-state-timeline-resolver/pull/14

feat: Add VizMSE Clear-all commands settings

---

meteor/client/lib/viewPort.ts
meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx

Does not use a hard-coded value for Header height, but instead attempts to measure it from the DOM.
The header height is a hard-coded constant, thus causing some problems with Follow On Air (broadly speaking).
The height of the header is measured when it's first used, allowing customizations of the header to not affect "Follow On Air".
Let me know if I should contribute this back to NRK as a PR or not.

fix: measure HEADER_HEIGHT value for viewPort intersection and scrollTo

---

meteor/server/api/playout/timeline.ts

This PR fixes an issue with getTimelineRundown.
If a ShowStyle blueprint function called `onTimelineGenerate` crashes when run by `getTimelineRundown` in `timeline.ts`, it can silently prevent playback of a newly taken part. The part becomes the current part and simulated initial playback in the GUI happens (based on the `taken` timestamp), but no actual playout by the playout gateway is done, because `updateTimeline` never finishes and no new timeline is generated. I do not belive this is acceptable behavior.
The call to `onTimelineGenerate` is wrapped in a …

fix: prevent a crash in getTimelineRundown by onTimelineGenerate

---

meteor/client/lib/EditAttribute.tsx
meteor/client/styles/editAttribute.scss
meteor/client/ui/Settings/ConfigManifestSettings.tsx

This PR adds support for JSON entries in Config Manifest. A new type of EditAttribute is added. It has simple validation to indicate when the entered value fails to parse as JSON.
Depends on https://github.com/olzzon/tv-automation-sofie-blueprints-integration/pull/2

feat: Add JSON config manifest entry with simple validation

---

meteor/lib/api/peripheralDevice.ts
meteor/server/api/integration/media-scanner.ts
meteor/server/api/peripheralDevice.ts

This PR adds a `clearMediaObjectCollection` method to the `PeripheralDeviceAPI`. This method allows removing documents from the MediaObjects collection, where the given `collectionId` and the `studioId` of the device match.
This is used by the Playout Gateway to manage MediaObjects used for reporting statuses of Viz elements.

Feat: clear media objects

---

meteor/server/api/ingest/rundownInput.ts

When the allowUnsyncedSegments setting is enabled, and a segment or a part is removed or updated, only the segment will get unsynced, instead of the rundown

fix: Unsync segments instead of the rundown when allowed

---

meteor/server/api/ingest/genericDevice/actions.ts
meteor/server/api/ingest/rundownInput.ts

This PR prevents segments from getting stuck, when they become unsynced because of removing from NRCS during their playback. When resyncing a segment, and the ingest gateway says the segment does not exist, we should remove it, because in this case, it most likely got unsynced because of being removed from the NRCS.

fix: Remove a segment when device can't find it

---

meteor/server/__tests__/codeControl.test.ts
meteor/server/api/ingest/actions.ts
meteor/server/api/ingest/expectedPlayoutItems.ts
meteor/server/api/ingest/mosDevice/ingest.ts
meteor/server/api/ingest/rundownInput.ts
meteor/server/api/playout/adlib.ts
meteor/server/api/playout/playout.ts
meteor/server/api/playout/take.ts
meteor/server/mockData/rundownData.ts

This PR fixes a performance issue related to updating ExpectedPlayoutItems, that is done in `updateExpectedPlayoutItemsOnRundown`, called at the end of the ingest methods.
`getAllPiecesFromCache` and `getAllAdLibPiecesFromCache`, performing `findFetch` on the cached collections, are executed for every Part, which makes the whole process extremely slow for long rundown because of the need for iterating over all the Pieces and AdlibPieces multiple times. O(m x n)
Pieces and AdLibPieces are fetched and grouped by their `startPartId` or `partId`. O(n)
In addition: 
- …

Perf: Ingest performance

---

meteor/lib/api/rundown.ts
meteor/lib/collections/Rundowns.ts
meteor/lib/collections/Segments.ts
meteor/server/api/ingest/__tests__/ingest.test.ts
meteor/server/api/ingest/mosDevice/ingest.ts
meteor/server/api/ingest/rundownInput.ts
meteor/server/api/rundown.ts

This PR adds logic that modifies the rank of a segment that was removed from the rundown in NRCS, but was live in Sofie and is left as unsynced. The implemented logic:
If there were no other stories in NRCS, and only the unsynced one left in Sofie, the unsynced one receives negative rank, and everything that's added later stays below that one. 
If there are other stories, the unsynced one glues to the previous one. If new segments are added after the previous one, they will be placed after the unsynced one. If we move the previous somewhere, the unsynced one will glue to the segment that was before the moved. Rare edge case: swaping the segments directly before and after the unsynced one will always …

Feat: Unsynced segment positioning

---

meteor/client/ui/Settings/RundownLayoutEditor.tsx
meteor/client/ui/Shelf/DashboardPanel.tsx
meteor/lib/api/rundownLayouts.ts
meteor/lib/collections/RundownLayouts.ts

Adds two properties to the DashboardPanel:
- _Current part can contain next pieces_ - makes custom tally behavior around finding next in current part (made specifically for the touch UI) optional
- _Indicate only one next piece per source layer_ - prevents double tally in most cases by limiting and prioritizing the pieces from the next part, if present

Feat: next tally settings

---

meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx

Bug fix.
Sometimes two segment might appear as next (green header). 
Bug should be fixed by comparing `ownNextPartInstance` in tracker's `checkUpdate` because this prop might be updated
in other run of the tracker's autorun than `playlist.nextPartInstanceId` was, which could result in a segment keeping its next class after another segment is set as next.

Fix: Potentially stuck next segment

---

meteor/lib/api/system.ts
meteor/lib/collections/PartInstances.ts
meteor/server/__tests__/cronjobs.test.ts
meteor/server/api/system.ts
meteor/server/cronjobs.ts

- remove reset partInstances that were taken out at least `cleanLimitTime` ms ago (50 days) and their part no longer exists
- remove pieceInstances of those partInstances
- add `runCronjob` SystemAPI method to trigger the cronjob routines on demand

feat: add cron job routines to clean up part- and piece instances

---

meteor/client/styles/customInstallation.scss
meteor/client/styles/shelf/dashboard-rundownView.scss
meteor/client/ui/RundownView.tsx
meteor/lib/api/playout.ts
meteor/lib/api/userActions.ts
meteor/server/api/blueprints/context/adlibActions.ts
meteor/server/api/playout/adlib.ts
meteor/server/api/playout/playout.ts
meteor/server/api/userActions.ts

- Tweaks styling: backgrounds and margins
- Fixes UI freezing on Takes, which was caused by tracker reruns on `SegmentTimelineContainer` due to the way Mini Shelf filter changes were detected
- Fixes Mini Shelf behavior: when a mini shelf adlib is queued from keyboard, but it's discarded (a part is set as next or a non-minishelf adlib is queued), it will be queued again when using the shortcuts, instead of advancing by one

fix: Mini Shelf tweaks and fixes

---

meteor/client/styles/shelf/externalFramePanel.scss
meteor/client/ui/RundownView.tsx
meteor/client/ui/Settings/components/FilterEditor.tsx
meteor/client/ui/Shelf/ExternalFramePanel.tsx
meteor/client/ui/Shelf/Shelf.tsx
meteor/lib/Settings.ts
meteor/lib/collections/RundownLayouts.ts

Enable _Take_ keyboard shortcut in the standalone Shelf view.
Add _Disable focus_ option to the External Frame dashboard panel, that prevents the iframe from hijacking focus.
Adds optional keyboard blur indicator to the standalone Shelf view. Disabled by default; enable with `disableBlurBorderInShelf: false` setting.

Feat: take from standalone shelf

---

meteor/lib/api/shapshot.ts
meteor/lib/api/userActions.ts
meteor/server/api/playout/__tests__/__snapshots__/api.test.ts.snap
meteor/server/api/playout/lib.ts
meteor/server/api/rundown.ts
meteor/server/api/snapshot.ts
meteor/server/api/userActions.ts

By default limit PartInstances and PieceInstances in rundown snapshot to only non-reset, or reset but no older than 24 hours;
Adds extra parameter to the method and the REST endpoint to get the full snapshot with older instances

Fix: Snapshot size

---

meteor/server/api/playout/__tests__/__snapshots__/api.test.ts.snap
meteor/server/api/playout/lib.ts

An update on PieceInstances with too broad selector was deferred after new pieceInstances may have been created (eg. when activating a playlist, when `resetRundownPlaylist` is called first), leading to displaying a Part with no Pieces.
Solution: make it reset only pieceInstances from partInstances existing at the time of execution
_Trust the snapshots next time_

fix: activation resetting current pieceInstances

---

meteor/client/ui/RundownView.tsx
meteor/client/ui/RundownView/RundownTiming/SegmentDuration.tsx
meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
meteor/client/ui/Settings/components/rundownLayouts/RundownViewLayoutSettings.tsx
meteor/lib/collections/RundownLayouts.ts

Adds _Static duration in Segment header_ option to Rundown View Layout. When enabled, it makes the segment duration in the segment header always show the planned duration instead of acting as a counter when the segment becomes live.

feat: add static segment duration option

---

meteor/server/api/ingest/rundownInput.ts

Fixes two bugs:
- Ingest operations on any segment causing pieces to disappear from the dynamically inserted part that is currently next.
- Ingest operations on the live segment causing loss of current partInstance if it was inserted dynamically.

Fix: Ingest breaking the live and next part

---

meteor/server/api/playout/playout.ts

segmentDelta > 0, we're going down, hence we consider segments with indexes higher than target
segmentDelta < 0, we're going up, hence we consider segments with indexes <= the target, and reverse the order

fix: moveNext when using segmentDelta

---

meteor/client/styles/customInstallation.scss

Fixes the segment duration to stay the same color no matter what the mode of the segment sidebar clocks is.

fix: dimming the segment duration (SOF-548)

---

meteor/server/api/ingest/rundownInput.ts

Currently, when media objects update we will not do anything to the segments. This is due to some missing code from the media object subscriptions work. This PR adds this code to re-run `getSegment`.

fix: Rerun getSegment when media object updates

---

meteor/__mocks__/meteor.ts
meteor/lib/__tests__/lib.test.ts
meteor/lib/lib.ts
meteor/server/api/systemTime/systemTime.ts

Change `getCurrentTime` for server environment to no longer subtract the diff calculated using the NTP server.
From now on we're assuming that the system clock on the server running Core is NTP-synced and accurate enough.
Diff calculation using NTP is kept for information purposes only. System status and logging is adjusted to reflect that.
Syncing the time between server and the client, and between server and peripheral devices stays as it was.

refactor: disable NTP time adjustment

---

meteor/__mocks__/helpers/database.ts
meteor/server/api/__tests__/rundownPlaylist.test.ts
meteor/server/api/playout/__tests__/__snapshots__/playout.test.ts.snap
meteor/server/api/rundownPlaylist.ts

This test was failing for three reasons:
- Test data had not been updated with the move to the `timing` type
- The sort function to produce the default rundown ordering was incorrect
- Rundown ordering now uses `externalId` rather than `_id`, so how the mock data is created needed to be updated, otherwise all of the rundowns had the same `externalId` and so got assigned the same ranks

fix: Failing rundownPlaylist test

---

meteor/client/lib/reactiveData/reactiveDataHelper.ts
meteor/client/ui/RundownView/RundownNotifier.tsx

This fixes an issue where the notification centre would have "phantom" notifications appear as you scroll through the rundown view. These notifications would state that the media object for e.g. a VO piece had not yet been loaded. This was due to the media object subscription not being ready yet.
This PR makes the notification centre wait until the media object subscription is ready before trying to evaluate the media object status for pieces.

fix: Missing media notifications shown while media subscription is not ready yet

---

meteor/client/ui/SegmentTimeline/SourceLayerItem.tsx

This fixes a bug where the hover scrub in the next part would advance on its own. This was due to the `scrollLeftOffset` pushing the current time along, despite the relative position of the cursor and div not changing in screen-space. I have stored the cursor position in the places we capture it and use that to re-calculate the time position.

fix: Re-evaluate cursor position as next part moves relative to cursor

---

meteor/server/api/playout/lib.ts
meteor/server/api/playout/playout.ts
meteor/server/api/playout/take.ts
meteor/server/api/userActions.ts

Bug fix in the Queued (Next) Segment feature
In various edge cases the queued segment starts looping infinitely (until cleared manually), or is queued an extra time.
Sample steps to reproduce the unwanted behavior:
Case 1:
- Take a Part in segment A
- Queue segment B
- Set first part of Segment B as next
- Queue Segment A twice
- Take - Segment A will loop until manually unqueued
Case 2:
- Take the first part in a segment (A) that has multiple parts
- Queue a segment (B) that has only one part
- Set as next segment B
- Take - Segment A will loop until manually unqueued
Case 3:
- Take the first part in a segment A, that has …

fix: Queued segment looping until cleared manually

---

meteor/server/api/blueprints/context/context.ts
meteor/server/api/blueprints/context/removeOrphanedPartInstance.ts
meteor/server/api/blueprints/context/syncIngestUpdateToPartInstance.ts
meteor/server/api/ingest/commit.ts
meteor/server/api/ingest/shouldRemoveOrphanedPartInstance.ts
packages/blueprints-integration/src/api.ts
packages/blueprints-integration/src/context.ts

This PR adds a showstyle blueprint method `shouldRemoveOrphanedPartInstance`. This method is called whenever the part associated with whatever is set as next is deleted.
If the blueprints want the part instance for next to be removed, and a new next to be found, they call a method on the context object passed to this function.
This function itself does not select a new next, as it is not expected to be used in isolation but as part of the commit phase of database operations, which ensure a safe next point before finalizing the commit.

feat: shouldRemoveOrphanedPartInstance

---

meteor/client/ui/RundownView.tsx
meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
meteor/client/ui/Settings/RundownLayoutEditor.tsx

Fixes an issue causing the filter defined in the Mini Shelf Layout to have no effect.
Fixes reactivity issues - the mini shelves didn't update on changes to the adlibs they display. Sidenote: This needs more work in the future - I dislike the idea of the `RundownViewShelf` being inside `SegmentTimelineContainer`. They seem to have nothing in common (except one tracked prop) to back up having this hierarchy.
Fixes an issue preventing population of Shelf Layout, Mini Shelf Layout and Rundown Header Layout inside Rundown View Layouts editor.

Fix: Minishelf filters not working

---

meteor/lib/api/rundownLayouts.ts

It adds support for text label filters in panel-based dashboard layouts.
Motivation for this is to use it as title for external frames (e.g. microphone tally).

fix: Added filter support for TEXT_LABEL to panel-based dashboard_layouts.

---

meteor/client/ui/RundownView/RundownTiming/PlaylistEndTiming.tsx

The diff counter would always floor the diff decimal causing it to show 00:00 twice.
Changed it to ceil the decimal when below 0 and floor when above 0
when diff in millis is:
-1529 would show -00:01, now it will show -00:02
-529 would show -00:00, now it will show -00:01
470 would show +00:00, now it will show +00:00
1470 would show +00:01, now it will show +00:02

fix: florr diff counter when below 0 and ceil if over

---

meteor/server/api/playout/__tests__/playout.test.ts
meteor/server/api/playout/cache.ts
meteor/server/api/playout/lib.ts

Fixes an issue leading to leftover non-reset partInstances from previous activations messing up the UI.
The new `activationId` is generated after resetting, so the correct behavior for the `resetRundownPlaylist` function is to
- remove rehearsal partInstances with the current activationId, and their pieceInstances
- reset partInstances with current activationId, and their pieceInstances

fix: resetting partInstances and pieceInstances

---

meteor/lib/__tests__/systemTime.test.ts
meteor/lib/lib.ts
meteor/lib/systemTime.ts
meteor/server/api/systemTime/startup.ts

Feature/improvement
When wall time (returned by `Date.now()`) jumps (or is gradually adjusted) by the OS where the client is running, previously calculated diff becomes no longer valid, but it will be updated only after certain amount of time passes (based of fixed interval and sync degradation calculation)
The added `TimeJumpDetector` class works both server- and client-side.
On the client, difference between wall clock and monotonic clock is computed every 10 seconds, and if they go out of sync by more than `TARGET_TIME_SYNC_QUALITY` (50ms), an immediate diff …

feat: Add time-jump detection

---

packages/playout-gateway/package.json
packages/yarn.lock

Bump versions in playout gateway to avoid version mismatch error messages in core

fix: bump version in playoutgateway to avoid error messages in core

---

meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
meteor/server/api/playout/take.ts

Bug fix.
Resync does not happen in commentator view.
Resync is moved to server side, and is performed whenver the take function is called to move us from one segment to another.
**Status**

fix: Move resync rundown on take into take function

---

meteor/client/ui/RundownView.tsx

Fixes issue where the next minishelf adLib would not be queued if the current live segment does not include any minishelf adLibs.
Bug fix.
It's currently not possible to queue the next minishelf adLib if the current segment does not include any minishelf adLibs.
If we can't find the current position in the `uiSegments` array, we will start searching from position `0`.
**Status**

SOF-725 fix: Minishelf not queuing next adLib

---

.github/workflows/node.yaml

Fixes failed github actions due to node 16 being used by default.

fix: Force node 12 for all actions steps

---

meteor/server/api/ingest/commit.ts
meteor/server/api/ingest/generation.ts

Bug fix.
When the live segment is floated, it is removed from the Sofie UI, and the underlying data is deleted.
The floated segment will be treated as "unsynced", with the contents preserved if `preserveUnsyncedPlayingSegmentContents` is set as a core config. If this setting is not set, only the current part instance will be preserved, in line with the current removal logic.
In either case, the live segment will remain visible until the user takes another segment, at which point it will be cleaned up.
Some logic has been moved from the generation stage to the commit …

fix: Live segment removed when floated

---

meteor/client/ui/PieceIcons/PieceIcon.tsx

Bug fix.
Parts containing a transition as the primary piece (e.g. KAM CS 3, Intros) are given an orange background in the presenter screen / part preview panel. This is due to transition layers not being included in the list of piece icon layers, so the first valid layer found ends up being a (hidden) graphics layer.
Transition layers are now allowed as primary layers, so pieces on these layers will be found and used as the primary piece.
**Status**

fix: Include transition pieces in primary piece lookup

---

meteor/client/lib/triggers/TriggersHandler.tsx
meteor/client/lib/triggers/codesToKeyLabels.ts
meteor/client/ui/RundownView.tsx
meteor/client/ui/RundownView/RundownViewEventBus.ts
meteor/client/ui/SegmentTimeline/Renderers/CustomLayerItemRenderer.tsx
meteor/client/ui/Settings/components/triggeredActions/actionEditors/actionSelector/ActionSelector.tsx
meteor/client/ui/Settings/components/triggeredActions/triggerEditors/HotkeyEditor.tsx
meteor/client/ui/Shelf/KeyboardPreview.tsx
meteor/client/ui/Shelf/KeyboardPreviewPanel.tsx
meteor/lib/api/rundownLayouts.ts
meteor/lib/api/triggers/actionFactory.ts
meteor/lib/api/triggers/actionFilterChainCompilers.ts
meteor/server/migration/1_37_0.ts
packages/blueprints-integration/src/triggers.ts

Merges latest commits from nrkno/release37.
Improves performance and feature set of TriggersHandler:
- makes each property of rundownPlaylistContext a reactive var to make preview trackers depend only on the really needed properties
- adds rundown view event for triggering mounted actions by their ids
- adds extra MountedGenericTriggers and MountedAdLibTriggers properties to facilitate use in the keyboard preview
Makes the Keyboard Preview (Keyboard Map) use Action Triggers.

SOF-510(SOF-717) feat: action triggers with keyboard map

---

meteor/client/ui/Shelf/AdLibPanel.tsx

Bundter were created as duplicated keyboard shortcuts.
Looks like it was caused by a merge error

fix: fixed duplicated shoutcuts

---

meteor/__mocks__/helpers/database.ts
meteor/lib/collections/Segments.ts
meteor/lib/rundownNotifications.ts
meteor/server/api/ingest/__tests__/ingest.test.ts
meteor/server/api/ingest/commit.ts
meteor/server/api/ingest/lib.ts
meteor/server/api/playout/lib.ts
meteor/server/codeControl.ts

- don't orphan too eagerly
- reingest orphaned:hidden segment after it goes off air
- preserve some properties when orphaning hidden segment (because we don't hide empty segments only - they may have minishelves)
- make the notification tell the real reason of being unsynced

fix: hidden segments disappearing forever

---

meteor/server/api/playout/actions.ts
meteor/server/api/playout/pieces.ts
meteor/server/api/playout/playout.ts
meteor/server/api/userActions.ts

Bug fix.
- If you queue the currently live segment, there is not indicator that it is next/queued.
- Deactivating a rundown does not clear the queued segment point.
- Setting the queued segment as next does not clear the queued segment.
The issues above are fixed.
**Status**

fix: Queued segment bugs

---

.gitignore
meteor/client/styles/customInstallation.scss
meteor/client/ui/FloatingInspectors/FloatingInspectorHelpers/FloatingInspectorTimeInformationRow.tsx
meteor/client/ui/FloatingInspectors/L3rdFloatingInspector.tsx
meteor/client/ui/FloatingInspectors/VTFloatingInspector.tsx

Bugfix SOF-678
Graphics hoverscrub no longer shows an empty "Clip:" if there is no information to be displayed.
The sourceLayerType "lower-third" now has the same colour as the "graphic" sourceLayerType for Tv2 and the hoverscrub for "lower-third" now displays time information about the piece

Fix/sof 678/disable hoverscrub popup

---

meteor/client/ui/RundownList.tsx

Was using an old property - `exposeAsShelf` - which does not exist anymore.
RundownView layouts now have `exposeAsSelectableLayout`, Shelf layouts now have `exposeAsStandalone`.

fix: selector preventing layout dropdown to show

---

meteor/client/styles/shelf/miniRundownPanel.scss
meteor/client/ui/Settings/components/FilterEditor.tsx
meteor/client/ui/Shelf/MiniRundownPanel.tsx
meteor/client/ui/Shelf/ShelfDashboardLayout.tsx
meteor/lib/api/rundownLayouts.ts
meteor/lib/collections/RundownLayouts.ts

This change allows users to add a panel to their dashboard showing a mini rundown with the current playing part and the next 3 parts.
[SOF-774](https://tv2cms.atlassian.net/browse/SOF-774)
Version 2

Feat/sof 774/qbox mini rundown view

---

meteor/server/api/blueprints/context/context.ts
packages/blueprints-integration/package.json
packages/blueprints-integration/src/context.ts

ITimlineEventContext now provides previousPartInstance as a seperate field

Sof 789/sisyfos accept persistence

---

meteor/client/styles/shelf/miniRundownPanel.scss
meteor/client/ui/Shelf/MiniRundownPanel.tsx

Fixes the following issues:
- Segments with `isHidden: true`(e.g. segments with no parts or floated segments) were shown
- When refreshing the page, current/next segment would not be scrolled into view
- It used a magic number that made the offset right only for one scale value

fix: SOF-858 mini rundown filtering and scrolling

---

meteor/client/lib/ModalDialog.tsx
meteor/client/lib/triggers/TriggersHandler.tsx
meteor/client/lib/ui/containers/modals/Modal.tsx

Modal dialogs can now be accepted with both Enter and NumpadEnter, via AnyEnter.

fix(SOF-910): Use AnyEnter instead of Enter for modals.

---

meteor/client/ui/Shelf/EndWordsPanel.tsx

Fix/hack to make endwords work again.
getIsFilterActive in [rundownLayouts.ts ](https://github.com/tv2/tv-automation-server-core/blob/50bda8aaae1d2793a903b1043afe88648532bf3e/meteor/client/lib/rundownLayouts.ts#L15) does not as it used to.
getUnfinishedPieceInstancesReactive does not return pieces for the script source layer it only return e.g. the pieces for the cam source layer or the server source layer.
There is also a problem with the filtering in getUnfinishedPieceInstancesReactive as stoppedPlayback on a piece is no longer set when the piece ends but when the segment ends. So you end up with two pieces with a value in startedPlayback and 0 in stoppePlayback. That's why I had to do all the filtering in the beginning of the function.
There is most like a correct way to fix all of …

fix: made a custom funtion to find piece with script

---

meteor/client/ui/Settings/SystemManagement.tsx
meteor/server/coreSystem.ts
meteor/server/logging.ts

In order to set a log level, instead of `silly`, at startup, setting log level from `LOG_LEVEL` env var was introduced.
The value set in the core system settings overrides this behaviour.
Silly log level is used if no other log level is specified.

feat: Set log level from LOG_LEVEL env var.

---

.github/workflows/node.yaml
meteor/__mocks__/helpers/database.ts
meteor/package.json
meteor/server/api/ingest/rundownInput.ts
meteor/yarn.lock
packages/blueprints-integration/package.json
packages/blueprints-integration/src/api.ts
packages/blueprints-integration/src/context.ts
packages/corelib/package.json
packages/corelib/src/worker/ingest.ts
packages/job-worker/package.json
packages/job-worker/src/blueprints/context/adlibActions.ts
packages/job-worker/src/blueprints/context/context.ts
packages/job-worker/src/ingest/generation.ts
packages/job-worker/src/ingest/rundownInput.ts
packages/job-worker/src/workers/ingest/jobs.ts
packages/playout-gateway/package.json
packages/server-core-integration/package.json
packages/yarn.lock

- Fixes some bugs that caused core to crash when mediaObjects were updated.
- Removes redundant `ReloadSegment` job in favour of `RegenerateSegment`.
- Makes `hackGetMediaObjectDuration` async to make it return the value (the previous `cursor.forEach` was an unhandled promise). Seemed like the easiest way without reengineering the whole thing. For our use case it only affects the return type of `getSegment` in the blueprint API.

fix: SOF-954 hackGetMediaObjectDuration

---

meteor/server/api/ingest/__tests__/ingest.test.ts
meteor/server/api/ingest/commit.ts

Cherry-pick of a fix from NRK. 
Fixes a bug that caused adlib partInstances (`orphaned: "adlib-part"`), including the one queued as next, to be marked as `orphaned: "deleted"` during any ingest operations, leading to some infinites missing when such part was taken.

fix: SOF-977 missing infinites in adlib-part after unrelated ingest operations

---

meteor/client/ui/RundownView.tsx

Fixes a race condition that sometimes caused the last adlib piece to be requeued when the next one should be queued instead.

fix: SOF-944 make MiniShelf hotkeys work consistently

---

meteor/client/styles/tv2/customInstallation.scss
meteor/client/ui/RundownView.tsx
meteor/client/ui/RundownView/RundownViewShelf.tsx
meteor/client/ui/SegmentContainer/withResolvedSegment.ts
meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
meteor/client/ui/Shelf/DashboardPieceButton.tsx
meteor/client/ui/Shelf/TimelineDashboardPanel.tsx

Make a single tap on a dashboard button toggle the adlib once. (Before, when `toggleOnSingleClick` was `true`, it toggled it twice, leading to a piece starting and almost immediately stopping afterwards)
Make the MiniShelf and TimelineDashboardPanel respect their filter's `toggleOnSingleClick` option.
Removes the `no-pointer` hack in favour of enabling `toggleOnSingleClick` on our dashboard panels, which was the intended way of making a single click/tap toggle adlibs (will come in a separate PR for the blueprints).

fix: SOF-769 adlib toggling with toggleOnSingleClick enabled

---

meteor/client/lib/triggers/TriggersHandler.tsx

Fixes a bug causing labels to disappear from the keyboard preview in some scenarios e.g. when changing ShowStyle settings.
When `isolatedAutorunWithCleanup` is called within an effect, the `currentComputation` might be stopped and replaced, triggering the cleanup, but the effect might not rerun due to the dependencies being identical. Manually stop trackers made with `isolatedAutorunWithCleanup` when no longer needed.

fix: SOF-1012 disappearing keyboard labels

---

meteor/client/ui/RundownView/RundownViewShelf.tsx

The ability to let minishelf toggle on single click was removed in a merge. This is re-introducing it.

SOF-1102 Minishelf now toggles on single click

---

meteor/client/ui/Settings/components/rundownLayouts/ShelfLayoutSettings.tsx
meteor/client/ui/Shelf/Shelf.tsx
meteor/client/ui/Shelf/ShelfContextMenu.tsx
meteor/lib/collections/RundownLayouts.ts
meteor/server/api/__tests__/rundownLayouts.test.ts

Adds a Shelf Layout option called _Hide default AdLib Start/Execute options_.
When enabled, the default items from AdLib's context menu (‘Start this AdLib’, ‘Queue this AdLib’ or ‘Execute’) will not be shown. Trigger modes for AdLib Actions will be shown, if defined. Other options related to buckets or the inspector will be shown if these features are enabled. If there are no options to be shown, the menu will not appear at all.
Example with buckets and inspector enabled, and no trigger modes:
Example with buckets and inspector disabled, and two trigger modes defined:
Example with buckets and inspector disabled, and no trigger modes: (no menu)

feat: SOF-767 add option to hide default Start/Execute context menu options for adlibs

---

packages/blueprints-integration/package.json
packages/playout-gateway/package.json
packages/yarn.lock

Cherrypick from develop. Includes a threadedclass and casparcg-state upgrades, and increases ping timeout durations in TSR.
Note: the tests pass but then the workflows fail with `Codecov: Failed to properly upload` - I think these are some temporary issues with their servers.

chore: SOF-1091 update TSR on Staging

---

meteor/client/lib/EditAttribute.tsx
meteor/client/lib/multiSelect.tsx
meteor/client/styles/multiSelect.scss
meteor/client/styles/settings.scss
meteor/client/ui/Settings/ConfigManifestSettings.tsx
meteor/client/ui/Settings/ShowStyleBaseSettings.tsx
packages/blueprints-integration/src/config.ts

Adds new config manifest entry type, called `ConfigManifestEntrySelectFromColumn`, which allows populating dropdowns (single or multiple choice) with all values from a column in a different (or the same) config table. 
for Show Style Variants, if the variant does not override the source table, values from the Base Show Style are used. 
For a table with the following text values,
the following dropdowns can be automatically populated in another table (or as a single config field)
If a value that was previously selected no longer exists in the source column, the dropdown will have a red border, and the option will be crossed out

feat: SOF-978 add `ConfigManifestEntrySelectFromColumn`

---

meteor/client/styles/rundownSystemStatus.scss
meteor/client/styles/rundownView.scss
meteor/client/styles/shelf/showStylePanel.scss
meteor/client/ui/Shelf/ShowStylePanel.tsx

I am unsure if i have placed the css in fitting locations - so that might be something that need changes.
And yes, i did run Tests before the commit, Rasmus :)
- fix: added ellipsis to Show style and Show style variant.
- fix: set width of div containing system status to 100% instead of pixel value, allowing tooltips on Show style and Show style variant to work.

SOF-1129: shortened names with use of ellipsis

---

meteor/server/migration/1_39_0.ts

Fixes a migration that was bothering me after Resetting All Versions. 
`expectedDuration` and `expectedDurationWithPreroll` can be undefined, but the migration did not consider that valid

fix: stuck Parts.expectedDurationWithPreroll migration

---

.github/workflows/node.yaml
meteor/package.json
meteor/server/migration/currentSystemVersion.ts
packages/blueprints-integration/package.json
packages/corelib/package.json
packages/documentation/package.json
packages/job-worker/package.json
packages/lerna.json
packages/mos-gateway/package.json
packages/playout-gateway/package.json
packages/server-core-integration/package.json
packages/shared-lib/package.json
packages/yarn.lock

Fixes the release-libs job to use our scope override hack in the `Check release is desired` step. Makes this job run on the workflow_dispath event (manualy by pressing the button on GitHub) so that we don't have to push to npm from local machines.
Sets version numbers to 46.0.0 so that we roughly know what we're using.

chore: Enable workflow_dispath for publishing to npm & bump to 46.0.0

---

.github/workflows/node.yaml
packages/blueprints-integration/package.json
packages/server-core-integration/package.json
packages/shared-lib/package.json
packages/yarn.lock
scripts/prepublish.js

Adds optional argument for overriding package scope in the prepublish.js script.
Updates some versions that I broke by pushing to npm libs dependent on the wrong shared-lib.

chore: Fix package scope overriding for npm packages

---

packages/blueprints-integration/package.json

Does not contain any code changes, but we need a new version because 46.0.2 got broken on NPM

chore: bump blueprints-integration to 46.0.3

---

meteor/client/ui/Settings/ShowStyle/VariantSettings.tsx
meteor/lib/api/showStyles.ts
meteor/server/api/showStyles.ts

Showstyle variants can now be copied to the bottom of the list, downloaded either as a single variant or all variants together, and imported as well. Imports also work with single variants as well as multiple.

Sof 1119/Copy Import Export Variants

---

meteor/server/api/ingest/rundownInput.ts
packages/mos-gateway/package.json

Now check if the Segment exists in IngestDataCache before telling to update from the cache. 
Removed linting of autogenerated js files that kept complaining about linting issues in MOS-gateway.

SOF-1144 Only update Segment from cache if the Segment exists in the cache

---

meteor/client/ui/App.tsx
meteor/client/ui/Shelf/Keyboard/KeyboardPreview.tsx
meteor/client/ui/globals/keyboardGlobals.d.ts

Keyboard globals no longer reside in the KeyboardPreview.
Keyboard interface now includes .lock() definition

SOF-1175 Move Keyboard globals

---

meteor/client/lib/EditAttribute.tsx
meteor/client/ui/Settings/components/ConfigManifestEntryComponent.tsx
packages/playout-gateway/src/configManifest.ts
packages/playout-gateway/src/tsrHandler.ts

PlaylistID for VizMSE device now has 'SOFIE' as default.
`defaultVal` values specified in the config manifest for devices will now send those values to the devices if there is no value configured.
The UI will display a text saying "Defaults to {value} if left empty" next to configuration field.
EditAttributeTextComponent now trims its own value, so a value like " " is no longer permitted.

Sof 1094/automate maintenance mse playlist

---

meteor/client/lib/triggers/TriggersHandler.tsx
meteor/client/ui/Settings/components/triggeredActions/TriggeredActionEntry.tsx
meteor/lib/collections/TriggeredActions.ts
meteor/server/migration/X_X_X.ts
packages/blueprints-integration/src/triggers.ts

Possible to use the label of the actionTrigger for the name shown in the keyboard layout of the shelf.
This is selected by ticking a new checkbox next to the label in the configuration of actiontriggers.
Due to how generic the action triggers are and the many possible different ways of creating actions triggers, just only works for most of them (But close to all).

Sof 1196/userdefined label on action trigger

---

meteor/__mocks__/helpers/database.ts
meteor/server/systemStatus/__tests__/systemStatus.test.ts

Fixes 4 tests failing if the blueprints integration version doesn't fit with core's version.
Also boyscouts/refactors away some duplicate code, with use of a helper method.

SOF-859: Removes need for matching version numbers for tests

---

meteor/package.json
meteor/server/worker/worker.ts
meteor/yarn.lock
packages/job-worker/package.json
packages/job-worker/src/ipc.ts
packages/job-worker/src/manager.ts
packages/job-worker/src/workers/events/parent.ts
packages/job-worker/src/workers/ingest/parent.ts
packages/job-worker/src/workers/parent-base.ts
packages/job-worker/src/workers/studio/parent.ts
packages/yarn.lock

Two bugfixes related to workers:
1. Upgrades threadedclass and uses its new properties to fix a bug where a timeout in child's constructor would cause the worker to be closed and never restarted again until the entire Core was restarted
3. Cherry-pick of a commit from NRK, fixing a bug where a force restart from within the worker loop would not trigger reintialization of the worker

fix: SOF-1203 worker autoRestart fixes

---

packages/job-worker/src/__mocks__/presetCollections.ts
packages/job-worker/src/playout/__tests__/playout.test.ts
packages/job-worker/src/playout/adlib.ts

Fixes a bug that caused queued adLib pieces (with `toBeQueued: true`) to start 'now' instead of being delayed when a transition was added to next partInstance

fix: SOF-1159 prevent queued piece from starting prematurely with in-transition

---

meteor/yarn.lock
packages/blueprints-integration/package.json
packages/playout-gateway/package.json
packages/playout-gateway/src/coreHandler.ts
packages/playout-gateway/src/tsrHandler.ts
packages/playout-gateway/src/tsrHandlerJobs/createDeviceJob.ts
packages/playout-gateway/src/tsrHandlerJobs/initCoreTsrHandlerJob.ts
packages/playout-gateway/src/tsrHandlerJobs/initDeviceJob.ts
packages/playout-gateway/src/tsrHandlerJobs/job.ts
packages/playout-gateway/src/tsrHandlerJobs/jobQueue.ts
packages/playout-gateway/src/tsrHandlerJobs/jobQueueManager.ts
packages/playout-gateway/src/tsrHandlerJobs/removeDeviceJob.ts
packages/playout-gateway/src/tsrHandlerJobs/setDebugLogging.ts
packages/playout-gateway/src/tsrHandlerJobs/setDebugLoggingJob.ts
packages/playout-gateway/src/tsrHandlerJobs/updateExpectedPlayoutItemsJob.ts
packages/yarn.lock

Fixes a bug that caused a device to be half-removed if its creation timed out, leaving it in an unwanted state that required user intervention. Refactors the device update logic, uses a queue to manage the actions. Some actions are broken down into multiple chained jobs to facilitate cleanup if one of the jobs fails or if the queue is cleared entirely (when settings of a device change before it's fully created and initialized, or a device pending creation is no longer needed)
Depends on https://github.com/tv2/tv-automation-state-timeline-resolver/pull/44

fix: SOF-1135 fix half removed device

---

packages/blueprints-integration/package.json
packages/playout-gateway/package.json
packages/playout-gateway/src/configManifest.ts
packages/yarn.lock

Exposes the bare minimum. Would be nice to have some dropdowns or other ways to prepopulate/validate the mapping target name, but the mappings are generated by the blueprints anyway, and there's type checking in there.
Depends on https://github.com/tv2/tv-automation-state-timeline-resolver/pull/46 (before merging this PR it needs bumping the TSR and TSR types after they're released)

feat: SOF-1272 expose TriCaster subdevice and mappings

---

meteor/yarn.lock
packages/playout-gateway/package.json
packages/playout-gateway/src/atemUploader.ts
packages/playout-gateway/src/connector.ts
packages/playout-gateway/src/coreHandler.ts
packages/playout-gateway/src/index.ts
packages/playout-gateway/src/influxdb.ts
packages/playout-gateway/src/logger/custom-json-format.ts
packages/playout-gateway/src/logger/index.ts
packages/playout-gateway/src/logger/logger.ts
packages/playout-gateway/src/process.ts
packages/playout-gateway/src/tsrHandler.ts
packages/playout-gateway/src/tsrHandlerJobs/createDeviceJob.ts
packages/playout-gateway/src/tsrHandlerJobs/initDeviceJob.ts
packages/playout-gateway/src/tsrHandlerJobs/jobQueue.ts
packages/playout-gateway/src/tsrHandlerJobs/jobQueueManager.ts
packages/playout-gateway/src/tsrHandlerJobs/removeDeviceJob.ts
packages/playout-gateway/src/tsrHandlerJobs/setDebugLoggingJob.ts
packages/playout-gateway/src/tsrHandlerJobs/updateExpectedPlayoutItemsJob.ts
packages/yarn.lock

The PR is a refactor of how we log:
- Ensure that the arguments that are given to the logger is given correctly (e.g. not a string as metadata object).
- Winston have been removed in favor of @tv2media/logger.
- Log statements are tagged with with the class/component that produced them.
- Errors and data is stored in the log attribute `data`, when applicable.
- `console.(warn|error|log)` is hijacked, and will state in the log message, that it was logged from a console method.

Sof 1337/playout gateway produces many useless logs

---

meteor/client/ui/Settings/ConfigManifestSettings.tsx
meteor/client/ui/Settings/helpers/config-manifest-table-entry-selector.ts
meteor/lib/Settings.ts
packages/blueprints-integration/src/config.ts

This PR has the purpose of making it possible to create the GFX Defaults table by filtering values from GFX Show Mapping. This required changes to blueprints-integration. It also makes it possible to have a table only hold a single row, thereby removing the ability to add and delete rows.

SOF 964/Accommodate Filtering for GFX Defaults

---

meteor/client/lib/editAttribute/edit-attribute-dropdown.tsx
meteor/client/lib/editAttribute/edit-attribute-multi-select.tsx
meteor/client/ui/Settings/helpers/show-style-variant-configuration-verifier.ts

EditAttributeDropdown and MultiSelect now updates their database entry when their selected option has a changed label.
When an attribute which was the target of a SELECT_FROM_COLUMN (or other similar ConfigEntries) had their values updated it was not reflected in the attributes that was targeting them. I.e. GfxDefaults was using GfxShowMappings to the get a Design and GfxShowMapping was getting the Design from the Design table. When the Design changed its name then GfxShowMapping didn't save the updated name in the database which meant that GfxDefaults was still getting the old Design name. 
The reason the database wasn't updated was because EditAttributeDropdown and EditAttributeMultiSelect only updated their data when the user selected a new value from their dropdown.
Now every time …

SOF-1240 Reflect attribute changes

---

meteor/client/ui/Settings/ConfigManifestSettings.tsx

With the new Dropdowns we no longer always get a string array but instead the array is sometimes an array of objects.
This fix makes it work with the array is full of objects.

No longer tries to place Object as a child for li

---

meteor/client/lib/editAttribute/edit-attribute-dropdown.tsx

When trying to add a new blueprints-configuration to a Studio or a Showstyle we would enter an inifite loop.
The loop happened because EditAttributeDropdown checks if the label has changed - if it has it will trigger an update.
The use of EditAttributeDropdown for adding blueprints-configurations does not have a label saved, so the label will always be changed. It also overrides the update function and make it call setState() which triggers a rerender, which triggers another check of if the label has changed and so forth.
Updated to only check if the label has changed if there is a saved value for label in the database.

SOF-1416 Don't check if label has changed if no label is saved to the database

---

meteor/client/ui/RundownView.tsx

After SOF-1240 we changed the datatype of the data selected by a dropdown. This new datatype is currently not supported by the entire RundownLayout code in the frontend. 
This is a hack/quickfix mapping the new datatype into the old, so layouts still work.
To fix it properly would be to change the interfaces to use the new datatype, which unfortunately is an too extensive task with our current deadlines...

SOF-1418 Map sourceLayerIds to a string array

---

package.json
scripts/run.js
yarn.lock

use the `--settings` argument, followed by file name of the json file with settings
example `yarn dev --settings C:\somepath\core-settings.json`

chore: allow meteor settings file to be provided to `yarn dev`

---

meteor/client/ui/Settings/ConfigManifestSettings.tsx

After we are able to decide wether or not the EditAttributeDropdown component will save the data with a label or not, we need to revert this usage of the EditAttributeDropdown back since it does no longer receive `{ value: string, label: string }`

SOF-1423 Revert updateFunction back to not fetch .value

---

meteor/client/ui/Settings/RundownLayoutEditor.tsx
meteor/lib/collections/optimizations.ts
meteor/server/api/__tests__/rundownLayouts.test.ts
meteor/server/api/rundownLayouts.ts

Makes it possible to upload shelf layouts for Show Styles associated with the given blueprint id so that we don't have to query Core for the id of the Show Style when automating this process. The first matching Show Style is chosen - a limitation due to the layouts having unique ids that wouldn't let the layout to be uploaded to more than one Show Style anyway (not a problem for us).
Also fixes use of an incorrect content type in the existing endpoint.

feat: SOF-1179 add endpoint for uploading shelf layouts by blueprint ID

---

meteor/client/ui/Settings/components/triggeredActions/actionEditors/filterPreviews/AdLibFilter.tsx

One of our dropdowns in the Action Triggers would fail because we tried to use the `in` operator on a String. We no longer try to do that.

SOF-1105 No longer tries to look for a 'value' attribute in a string

---

meteor/client/ui/Shelf/ShelfDashboardLayout.tsx
meteor/client/ui/Shelf/ShelfRundownLayout.tsx
meteor/client/ui/Shelf/utils/interpolatePanelStrings.ts
meteor/lib/Settings.ts
meteor/lib/collections/RundownLayouts.ts
meteor/package.json
meteor/yarn.lock

When `interpolateStringsInLayouts` setting is enabled, selected panel props in the Shelf will be treated as templates and values from the `studio` and `showStyleBase` will be resolved. 
This removes then need for having different Shelf layouts in each installation due to things like external frame URLs. Now such URL can look like this: `multiview.{{studio.settings.sofieUrl}}`.

feat: SOF-1213 string interpolation in Shelf layouts

---

meteor/client/styles/shelf/dashboard.scss
meteor/client/styles/shelf/miniRundownPanel.scss
meteor/client/styles/tv2/keyboardPreview.scss
meteor/client/ui/Settings/components/FilterEditor.tsx
meteor/client/ui/Shelf/DashboardPanel.tsx
meteor/client/ui/Shelf/Keyboard/KeyboardPreview.tsx
meteor/client/ui/Shelf/NextInfoPanel.tsx
meteor/client/ui/Shelf/PieceCountdownPanel.tsx
meteor/lib/collections/RundownLayouts.ts

Makes positioning in the dashboard more consistent. 
`scale` no longer affects the dimensions and positioning of the panel, only their contents.
Default font-size in is now panels is 1rem.
Current layouts that use `em` positioning may need to be updated if they also used `scale` other than 1 (or 0). Because this is a manual process, no migrations are made to automatically change `em` to `rem`.

fix: SOF-1181 position dashboard panels based on `rem` instead of `em`

---

meteor/client/ui/Shelf/Renderers/L3rdListItemRenderer.tsx
packages/blueprints-integration/src/rundown.ts
packages/corelib/src/playout/infinites.ts
packages/job-worker/src/playout/adlib.ts

Adds new piece lifespan called `OutOnRundownChangeWithSegmentLookback`. A piece with this lifespan follows the playhead like an `OutOnRundownChange` piece, but starts like an `OutOnSegmentEnd` piece (it will start when it's in a Part preceding the Part through which the segment was entered).

feat: add OutOnRundownChangeWithSegmentLookback lifespan

---

packages/corelib/src/playout/__tests__/pieces.test.ts
packages/corelib/src/playout/pieces.ts
packages/job-worker/src/playout/__tests__/timeline.test.ts
packages/job-worker/src/playout/timeline/part.ts
packages/job-worker/src/playout/timeline/piece.ts
packages/job-worker/src/playout/timeline/rundown.ts

Fixes the case of an infinite piece continuing from a previous part not being effective on the timeline (although visible in the UI) when the taken part has a piece with non-zero start time on the same layer

fix: infinites continuations capped too soon by pieces with non-zero start
