- meteor/server/api/ingest/__tests__/ingest.test.ts
- meteor/server/api/ingest/rundownInput.ts
This came up after testing by Kenneth.
This PR makes the rundown go unsynced if the currently playing segment or part is removed
> unsync on segment or part removal

- meteor/client/ui/SegmentTimeline/SourceLayerItemContainer.tsx
- meteor/client/ui/Shelf/AdLibListItem.tsx
- meteor/client/ui/Shelf/DashboardPanel.tsx
- meteor/client/ui/Shelf/DashboardPieceButton.tsx
- meteor/server/api/playout/infinites.ts
- meteor/server/api/playout/pieces.ts
Fixes toggling of dashboard buttons by selecting the right infinites to look at and fixing a crash in subscribing to the media objects collection.
> fix: Dashboard button state

- meteor/server/cronjobs.ts
This PR adds a cleanup routine for AsRunLog, UserActionsLog and Snapshots.
> feat: clean up old database entries

- meteor/client/styles/shelf/shelf.scss
- meteor/client/ui/Shelf/Shelf.tsx
* **What kind of change does this PR introduce?**
This PR makes the shelf handle work with touch screens, and prevents accidental closing of the shelf when the handle is quickly dragged in upward direction.
* **What is the current behavior?**
Shelf handle not responding to touch.
When the shelf is open, quickly dragging the handle in upward direction closes the shelf.
* **What is the new behavior?**
Shelf handle is responding to touch.
Only quickly dragging in downward direction closes the shelf.
> Fix: Shelf handle behaviour

- meteor/client/styles/shelf/externalFramePanel.scss
- meteor/client/ui/Settings/RundownLayoutEditor.tsx
- meteor/client/ui/Shelf/ExternalFramePanel.tsx
- meteor/lib/collections/RundownLayouts.ts
* **What kind of change does this PR introduce?**
This PR adds ability to apply CSS scaling to the iframe in an ExternalFramePanel, in order to be able to fit external contents better into the shelf layout.
Note that the transformation is applied after rendering the content in original resolution, so it may not look perfectly sharp.
> feat: Scaling of ExternalFramePanels

- meteor/client/lib/downloadBlob.ts
- meteor/client/lib/hotkeyRegistry.ts
- meteor/client/lib/mousetrapHelper.ts
- meteor/client/styles/keyboardPreview.scss
- meteor/client/styles/shelf/adLibPanel.scss
- meteor/client/ui/RundownList.tsx
- meteor/client/ui/RundownView.tsx
- meteor/client/ui/Settings/ShowStyleBaseSettings.tsx
- meteor/client/ui/Shelf/AdLibListItem.tsx
- meteor/client/ui/Shelf/AdLibPanel.tsx
- meteor/client/ui/Shelf/GlobalAdLibPanel.tsx
- meteor/client/ui/Shelf/KeyboardPreview.tsx
- meteor/client/ui/Shelf/KeyboardPreviewPanel.tsx
- meteor/client/ui/Shelf/Shelf.tsx
- meteor/lib/Settings.ts
- meteor/lib/collections/ShowStyleBases.ts
- meteor/lib/keyboardLayout.ts
- meteor/lib/tv2/AHKkeyboardMap.ts
This PR implements the "Interactive keyboard preview" feature
Functions (system, adLib's and others) assigned to various keys can be previewed and triggered from a simulation of a keyboard.
> feat: interactive keyboard

- meteor/client/styles/systemStatus.scss
- meteor/client/ui/RundownList.tsx
This PR fixes spacing between headers in the Rundown List table, and fixes the colspan of the progress bars on that list.
> Fix: Rundown List headers and progress bars

- meteor/client/styles/_itemTypeColors.scss
- meteor/client/styles/customInstallation.scss
- meteor/client/styles/defaultColors.scss
- meteor/client/ui/PieceIcons/Renderers/SplitInput.tsx
- meteor/client/ui/Settings/ShowStyleBaseSettings.tsx
- meteor/package-lock.json
- meteor/package.json
This PR adds support for `SourceLayerType.LOCAL`, and gives pieces from Source Layers of that type a custom color.
> Feat: SourceLayerType.LOCAL

- meteor/__mocks__/tracker.ts
- meteor/client/lib/VirtualElement.tsx
- meteor/client/lib/__tests__/rundown.test.ts
- meteor/client/lib/reactiveData/__tests__/reactiveDataHelper.test.ts
- meteor/client/lib/reactiveData/reactiveDataHelper.ts
- meteor/client/lib/rundown.ts
- meteor/client/ui/RundownView.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
- meteor/package-lock.json
- packages/yarn.lock
This is a new feature
All segments update as soon as possible
This will randomize the refreshes of non-live-or-next segments in a 2000ms window, 500ms after a take when a rundown is active, which should increase the responsiveness of the GUI.
**Status**
> feat: use staggered updates for non-current segments

- meteor/server/api/playout/__tests__/playout.test.ts
- meteor/server/api/playout/lib.ts
- meteor/server/api/playout/take.ts
More fixes regarding resetting partInstances and pieceInstances:
- When resetting/removing pieceInstances use the collection directly because the cache does not contain all relevant pieceInstances
- When taking, reset old PartInstances and PieceInstances of the taken Part, that were excluded from resetting in setNextPart
> fix: resetting partInstances and pieceInstances

- meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
Port of https://github.com/nrkno/tv-automation-server-core/pull/581 to TV2s codebase.
> fix: rewind bug for mirror/release37

- meteor/client/ui/RundownView/RundownDividerHeader.tsx
- meteor/client/ui/RundownView/RundownTiming/AutoNextStatus.tsx
- meteor/client/ui/RundownView/RundownTiming/CurrentPartElapsed.tsx
- meteor/client/ui/RundownView/RundownTiming/CurrentPartRemaining.tsx
- meteor/client/ui/RundownView/RundownTiming/RundownTiming.ts
- meteor/client/ui/RundownView/RundownTiming/RundownTimingProvider.tsx
- meteor/client/ui/RundownView/RundownTiming/withTiming.tsx
- meteor/client/ui/SegmentTimeline/BreakSegment.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
- meteor/client/ui/SegmentTimeline/SegmentTimelinePart.tsx
- meteor/client/ui/Shelf/PieceCountdownPanel.tsx
- meteor/client/ui/examples.tsx
This is a work-in-progress PR to sync the ticking of various timers in the UI.
> feat: synced time displays

- meteor/client/styles/rundownSystemStatus.scss
changed text color in system status from grey to white to make it more visible
> fix: changed text color in system status from grey to white

- meteor/client/styles/_itemTypeColors.scss
- meteor/client/styles/customInstallation.scss
changed color of missing clip to red to make it easier to tell them apart from broken clips
> Color of missing video clips

- meteor/server/api/peripheralDevice.ts
Based on https://github.com/nrkno/sofie-core/pull/648, but ported from higher release
> fix: SOF-820 performance in timelineTriggerTime

- meteor/client/styles/main.scss
- meteor/client/styles/shelf/shelf.scss
- meteor/client/ui/Shelf/DashboardPieceButton.tsx
- meteor/client/ui/Shelf/Shelf.tsx
- meteor/package-lock.json
Cherry picked this commit https://github.com/nrkno/sofie-core/commit/c2f96945379bb9052dcd7d8dfe82e641136fd4c5
It seems to have fixed the issues with selecting elements in the commentator dashboard when using a touch screen.
It works on the touch screen I have on my PC.  I've also tried rolling back to master branch and then the issue comes back again
> fix: cherry pick c2f96945379b to fix touch issue

- meteor/client/lib/triggers/TriggersHandler.tsx
- meteor/client/ui/RundownView.tsx
- meteor/lib/Settings.ts
Takes a key string or null for enabling/disabling poisonKey for key bindings.
> fix: Added poisonKey flag.

- meteor/client/lib/triggers/TriggersHandler.tsx
- meteor/package-lock.json
- meteor/package.json
Using `preventDefaultDown: true` option for Sorensen, to prevent default behaviour on keyDown for up bound triggers.
> fix: Bumped Sorensen and using preventDefaultDown option.

- meteor/client/ui/RundownView.tsx
- meteor/client/ui/Shelf/Shelf.tsx
Instantiates a TriggersHandler when having `onlyShelf`.
Shelf component listens for soft take.
> Sof 856/kommentator view not triggering shortcuts

- meteor/package-lock.json
- meteor/package.json
Update Sorensen to 1.4.2 in order to get fix for the bug: [preventDefaultDown not respecting global option.](https://github.com/nrkno/sorensen/pull/3)
> fix(SOF-912): Bumped Sorensen for fixing preventDefaultDown not respecting global.

- meteor/client/ui/RundownView.tsx
- meteor/yarn.lock
These changes are some @KvelaGorrrrnio implemented in times past
> SOF-924 Select ShowStyle based on the current rundown

- meteor/yarn.lock
- packages/blueprints-integration/package.json
- packages/playout-gateway/package.json
- packages/yarn.lock
Bumps TSR to include a fix for ATEM transition that resets itself
> chore: SOF-1046 bump TSR

- meteor/package.json
- meteor/yarn.lock
- packages/blueprints-integration/package.json
- packages/job-worker/package.json
- packages/playout-gateway/package.json
- packages/yarn.lock
Downgrading superfly-timeline to 8.2.1 since it contains a bug that Core is abusing....
> fix: SOF-1031 Downgrade superfly-timeline to 8.2.1

- meteor/CHANGELOG.md
- meteor/client/ui/RundownView.tsx
- meteor/lib/api/userActions.ts
- meteor/package.json
- meteor/server/api/integration/rabbitMQ.ts
- meteor/server/api/userActions.ts
- meteor/server/worker/worker.ts
- meteor/yarn.lock
- packages/blueprints-integration/CHANGELOG.md
- packages/blueprints-integration/package.json
- packages/corelib/package.json
- packages/corelib/src/worker/studio.ts
- packages/job-worker/package.json
- packages/job-worker/src/events/handle.ts
- packages/job-worker/src/playout/debug.ts
- packages/job-worker/src/workers/events/parent.ts
- packages/job-worker/src/workers/ingest/parent.ts
- packages/job-worker/src/workers/locks.ts
- packages/job-worker/src/workers/parent-base.ts
- packages/job-worker/src/workers/studio/jobs.ts
- packages/job-worker/src/workers/studio/parent.ts
- packages/mos-gateway/CHANGELOG.md
- packages/mos-gateway/package.json
- packages/package.json
- packages/playout-gateway/CHANGELOG.md
- packages/server-core-integration/CHANGELOG.md
- packages/yarn.lock
- yarn.lock
Mainly it brings some critical fixes regarding threadedclass.
> fix: Release41 fixes from NRK

- packages/blueprints-integration/package.json
- packages/playout-gateway/package.json
- packages/yarn.lock
Updates TSR to get bugfixes in casparcg-state
> chore: SOF-767 update TSR

- meteor/lib/lib.ts
- packages/blueprints-integration/package.json
- packages/job-worker/src/ipc.ts
- packages/job-worker/src/workers/parent-base.ts
- packages/playout-gateway/package.json
- packages/playout-gateway/src/configManifest.ts
- packages/playout-gateway/src/coreHandler.ts
- packages/playout-gateway/src/tsrHandler.ts
- packages/yarn.lock
- TSR is bumped to 2.1.8 (https://github.com/tv2/tv-automation-state-timeline-resolver/pull/36).
- Logs have been improved:  Errors are now assigned to the data meta key, instead of each character in the stringified error being a key-value pair on the log object.
- Minor refactors of code.
> Sof 1135/threadedclass stability improvements

- meteor/lib/lib.ts
- packages/blueprints-integration/package.json
- packages/job-worker/src/ipc.ts
- packages/job-worker/src/workers/parent-base.ts
- packages/playout-gateway/package.json
- packages/playout-gateway/src/coreHandler.ts
- packages/playout-gateway/src/tsrHandler.ts
- packages/yarn.lock
Fix conflicts between stagin and develop so our automerge can work again.
Also, it merges staging into develop.
> Fix automerge staging to develop

- meteor/yarn.lock
- packages/blueprints-integration/package.json
- packages/playout-gateway/package.json
- packages/playout-gateway/src/tsrHandler.ts
- packages/yarn.lock
Port for https://github.com/nrkno/sofie-core/pull/766 and a few refactors.
> Sof 1135/remove uninitiliazed tsr devices from the list

- packages/playout-gateway/package.json
- packages/yarn.lock
Contains new version of v-connection
(the multiple-versions-check will complain because the release steps for TSR don't bump types if there are no changes - gotta fix that some day)
> chore: SOF-1140 bump TSR

- meteor/.eslintrc.js
- meteor/client/ui/Shelf/Keyboard/KeyboardPreview.tsx
Reenable no-duplicate-enum-value. Refactor away from duplicate enum value
> SOF-1182 Reenable no-duplicate-enum-values

- meteor/client/ui/Settings/ShowStyle/VariantSettings.tsx
The Showstyle Variants Settings page now says 'Show Style Variants' instead of 'Variants' and 'Name' instead of 'Variant Name'.
> SOF-1241: Reapplies changes lost in NRK Merge.

- packages/job-worker/src/ingest/expectedMediaItems.ts
- packages/job-worker/src/ingest/expectedPackages.ts
Also look in the RundownbaselineAdlibActions and RundownbaselineAdlibPieces for expected media items
> SOF-1242 Ingest media baseline adlib wipes

- meteor/client/ui/Shelf/DashboardPanel.tsx
- meteor/yarn.lock
Apply font-size based on the --dashboard-panel-scale to all panels in the Dashboard
> SOF-1278  Sofie clock is scaled incorrectly

- meteor/package.json
- meteor/server/migration/1_46_1.ts
- meteor/server/migration/X_X_X.ts
- meteor/server/migration/currentSystemVersion.ts
- meteor/server/migration/migrations.ts
- packages/blueprints-integration/package.json
- packages/corelib/package.json
- packages/documentation/package.json
- packages/job-worker/package.json
- packages/lerna.json
- packages/mos-gateway/package.json
- packages/playout-gateway/package.json
- packages/server-core-integration/package.json
- packages/shared-lib/package.json
Bump versions to 46.1.0. 
Create 46.1 migration file
> chore: SOF-1281 46.1 version bump

- meteor/client/ui/Settings/SystemManagement.tsx
- meteor/client/ui/Settings/helpers/config-manifest-table-entry-selector.ts
- meteor/client/ui/Settings/helpers/show-style-variant-configuration-verifier.ts
- meteor/yarn.lock
ShowStyleVariantConfigurationVerifier now supports SELECT_FROM_TABLE_ENTRY_WITH_COMPARION_MAPPINGS
> SOF-964 ShowStyleVariantConfigurationVerifier now supports SELECT_FROM_TABLE_ENTRY_WITH_COMPARION_MAPPINGS

- meteor/__mocks__/helpers/database.ts
- meteor/client/lib/editAttribute/edit-attribute-dropdown.tsx
- meteor/client/lib/editAttribute/edit-attribute-enum-dropdown.tsx
- meteor/client/lib/editAttribute/edit-attribute-multi-select.tsx
- meteor/client/ui/RundownView.tsx
- meteor/client/ui/Settings/ConfigManifestSettings.tsx
- meteor/client/ui/Settings/ShowStyleBaseSettings.tsx
- meteor/client/ui/Settings/Studio/Generic.tsx
- meteor/client/ui/Settings/Studio/Mappings.tsx
- meteor/client/ui/Settings/StudioSettings.tsx
- meteor/server/api/buckets.ts
- meteor/server/api/organizations.ts
- meteor/server/api/snapshot.ts
- meteor/server/coreSystem.ts
- meteor/server/migration/0_1_0.ts
- meteor/yarn.lock
- packages/corelib/src/dataModel/Studio.ts
- packages/job-worker/src/blueprints/__tests__/config.test.ts
- packages/job-worker/src/ingest/__tests__/ingest.test.ts
- packages/job-worker/src/ingest/mosDevice/__tests__/mosIngest.test.ts
- packages/job-worker/src/workers/caches.ts
- packages/job-worker/src/workers/context.ts
EditAttributeDropdown and EditAttributeDropdownMultiSelect now support saving values both with and without ids.
Reverted back some changes that no longer needs to load the data from the database with ids.
> Sof 1421/only save ids for select from attributes

- meteor/client/ui/Settings/helpers/config-manifest-table-entry-selector.ts
Update: All dependent PRs has been merged
OBS: Dependent on PR #239
ConfigManifestTableEntrySelector now filters away duplicates when fetching options for comparison.
> Sof 1417/list of schema has duplicates

- meteor/client/ui/RundownView.tsx
Adds dialog confirming rundown reset (triggered by the action trigger and the header context menu)
> feat: SOF-1375 add rundown reset confirmation dialog
